name: lily-env tests

on:
  push:
    branches:
      - feature/github-actions

jobs:
  test:
    name: Testing job
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        working-directory: .
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Launch tests
        working-directory: .
        run: py.test --cov=./lily_env --cov-config .coveragerc -r w -s -vv tests
